mmd_bone_map = {
    "all_parents_bone": "全ての親",
    "center_bone": "センター",
    "groove_bone": "グルーブ",
    "hip_bone": "腰",
    "upper_body_bone": "上半身",
    "upper_body1_bone": "上半身1",
    "upper_body2_bone": "上半身2",
    "upper_body3_bone": "上半身3",
    "neck1_bone": "首1",
    "neck_bone": "首",
    "head_bone": "頭",
    "left_shoulder_bone": "肩.L",
    "right_shoulder_bone": "肩.R",
    "left_upper_arm_bone": "腕.L",
    "right_upper_arm_bone": "腕.R",
    "left_lower_arm_bone": "ひじ.L",
    "right_lower_arm_bone": "ひじ.R",
    "left_hand_bone": "手首.L",
    "right_hand_bone": "手首.R",
    "lower_body_bone": "下半身",
    "left_thigh_bone": "足.L",
    "right_thigh_bone": "足.R",
    "left_calf_bone": "ひざ.L",
    "right_calf_bone": "ひざ.R",
    "left_foot_bone": "足首.L",
    "right_foot_bone": "足首.R",
    "left_toe_bone": "つま先.L",
    "right_toe_bone": "つま先.R",
    "control_center_bone": "操作中心",
    "left_eye_bone": "目.L",
    "right_eye_bone": "目.R",
    "left_thumb_0": "親指０.L",
    "left_thumb_1": "親指１.L",
    "left_thumb_2": "親指２.L",
    "right_thumb_0": "親指０.R",
    "right_thumb_1": "親指１.R",
    "right_thumb_2": "親指２.R",
    "left_index_1": "人指１.L",
    "left_index_2": "人指２.L",
    "left_index_3": "人指３.L",
    "right_index_1": "人指１.R",
    "right_index_2": "人指２.R",
    "right_index_3": "人指３.R",
    "left_middle_1": "中指１.L",
    "left_middle_2": "中指２.L",
    "left_middle_3": "中指３.L",
    "right_middle_1": "中指１.R",
    "right_middle_2": "中指２.R",
    "right_middle_3": "中指３.R",
    "left_ring_1": "薬指１.L",
    "left_ring_2": "薬指２.L",
    "left_ring_3": "薬指３.L",
    "right_ring_1": "薬指１.R",
    "right_ring_2": "薬指２.R",
    "right_ring_3": "薬指３.R",
    "left_pinky_1": "小指１.L",
    "left_pinky_2": "小指２.L",
    "left_pinky_3": "小指３.L",
    "right_pinky_1": "小指１.R",
    "right_pinky_2": "小指２.R",
    "right_pinky_3": "小指３.R",
}
mmd_bone_group = [
    {
        "name": "センター",
        "bones": [
            "全ての親",
            "センター",
            "グルーブ",
            "腰",
            "操作中心"
        ]
    },
    {
        "name": "ＩＫ",
        "bones": [
            "足IK親.R",
            "足ＩＫ.R",
            "つま先ＩＫ.R",
            "足IK親.L",
            "足ＩＫ.L",
            "つま先ＩＫ.L"
        ]
    },
    {
        "name": "体(上)",
        "bones": [
            "上半身",
            "上半身1",
            "上半身2",
            "上半身3",
            "首",
            "頭",
            "目.R",
            "目.L",
            "両目",
            "左眉中",
            "右眉中",
            "右眉頭",
            "左眉頭",
            "右眉尾",
            "左眉尾",
            "上齿",
            "下齿",
            "舌1",
            "舌2",
            "舌3",
            "舌4"
        ]
    },
    {
        "name": "腕",
        "bones": [
            "肩P.L",
            "肩.L",
            "腕.L",
            "腕捩.L",
            "ひじ.L",
            "手捩.L",
            "手首.L",
            "ダミー.L",
            "肩P.R",
            "肩.R",
            "腕.R",
            "腕捩.R",
            "ひじ.R",
            "手捩.R",
            "手首.R",
            "ダミー.R"
        ]
    },
    {
        "name": "指",
        "bones": [
            "親指０.L",
            "親指１.L",
            "親指２.L",
            "人指１.L",
            "人指２.L",
            "人指３.L",
            "中指１.L",
            "中指２.L",
            "中指３.L",
            "薬指１.L",
            "薬指２.L",
            "薬指３.L",
            "小指１.L",
            "小指２.L",
            "小指３.L",
            "親指０.R",
            "親指１.R",
            "親指２.R",
            "人指１.R",
            "人指２.R",
            "人指３.R",
            "中指１.R",
            "中指２.R",
            "中指３.R",
            "薬指１.R",
            "薬指２.R",
            "薬指３.R",
            "小指１.R",
            "小指２.R",
            "小指３.R"
        ]
    },
    {
        "name": "体(下)",
        "bones": [
            "下半身"
        ]
    },
    {
        "name": "足",
        "bones": [
            "足.L",
            "ひざ.L",
            "足首.L",
            "つま先.L",
            "足D.L",
            "ひざD.L",
            "足首D.L",
            "足先EX.L",
            "足.R",
            "ひざ.R",
            "足首.R",
            "つま先.R",
            "足D.R",
            "ひざD.R",
            "足首D.R",
            "足先EX.R"
        ]
    },
    {
        "name": "その他",
        "bones": [
            "右目先",
            "左目先"
        ]
    }
]
